# SERVER PORT
server:
  port: 8080
# LOGGING CONFIGS
logging:
  config: classpath:logback-local.xml
  level:
    com:
      zaxxer:
        hikari:
          HikariConfig: DEBUG
    org:
      hibernate:
        SQL: DEBUG
        stat: debug
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

# SPRING CONFIGS : DATABASE, JPA , MULTIPART
spring:
  datasource:
    url: jdbc:h2:mem:testdb;MODE=MySQL;
    username: sa
    password: sa
    driver-class-name: org.h2.Driver
    hikari:
      connection-timeout: 5000
      idle-timeout: 5000
      maximum-pool-size: 10
      minimum-idle: 3
      connection-test-query: SELECT 0
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        format_sql: true
#        show_sql: true
        use_sql_comments: true
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
      quiet-period: 1s
      poll-interval: 2s
  h2:
    console:
      enabled: true
#  servlet:
#    multipart:
#      enabled: true
#      file-size-threshold: 10MB
#      max-file-size: 200MB
#      max-request-size: 215MB
